### ISSUE TITLE
Make defaults function be a module attribute

### ISSUE THREAD

**Issue by tteerawat** [zentetsukenz/ping_plug#2]
Since `defaults` function always returns the same result, I think we can make it a `module attribute` so it will only be evaluated  at compile time.

https://www.erlang-solutions.com/blog/elixir-module-attributes-alchemy-101-part-1.html

**Comment by zentetsukenz** [comment]
Thanks @teerawat1992 will add this tonight.

**Comment by zentetsukenz** [comment]
https://github.com/zentetsukenz/ping_plug/pull/4
